version: "3.9"

services:
  react-app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Ensure custom nginx.conf is included
    restart: always
